### ISSUE TITLE
patched?

### ISSUE THREAD

**Issue by cptmacp** [danielkrupinski/VAC-Bypass#29]
is this exploit patched?

**Comment by ghost** [comment]
yes

**Comment by rokky15** [comment]
why do you think so

**Comment by orzobinbo** [comment]
well in my case I managed to inject into steam no problem, however when I trying to reconnect it just gets stuck loading on "Connecting Steam account: *********". 
But I could be because I tried injecting twice (@danielkrupinski ?). First time I injected I didn't have the "remember me" ticked, so I wasnt sure and decided to re-inject. Really not sure if that's why it get stuck on loading.

EDIT: with the loader however, steam launches without any issues.

**Comment by danielkrupinski** [comment]
Nope
